library(lubridate)
powerData <- read.table("household_power_consumption.txt", sep=";", header = TRUE, na.strings = c("?",NA))
powerData$Date <- as.Date(as.character(powerData$Date), format="%d/%m/%Y")
subPowerData <- subset(powerData, Date>=as.Date("2007-02-1", format="%Y-%m-%d") & Date<=as.Date("2007-02-02", format="%Y-%m-%d"))
datetime <- paste(as.character(subPowerData$Date),as.character(subPowerData$Time))
png(filename = "plot4.png",width = 480, height=480)
par(mfrow=c(2,2))
with(subPowerData, plot(ymd_hms(datetime),Global_active_power, type="n", xlab = "datetime", ylab = "Global Active Power (kilowatts)"))
lines(ymd_hms(datetime),subPowerData$Global_active_power)
with(subPowerData, plot(ymd_hms(datetime),Voltage, type="n", xlab = "datetime", ylab = "Voltage"))
lines(ymd_hms(datetime),subPowerData$Voltage)
with(subPowerData, plot(ymd_hms(datetime),Sub_metering_1, type="n", xlab = "datetime", ylab = "Energy sub meeting"))
lines(ymd_hms(datetime),subPowerData$Sub_metering_1)
lines(ymd_hms(datetime),subPowerData$Sub_metering_2, col="red")
lines(ymd_hms(datetime),subPowerData$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub_meetering_1","Sub_meetering_2","Sub_meetering_3"), col=c("black","red","blue"),lty=c(1,1,1),bty="n")
with(subPowerData, plot(ymd_hms(datetime),Global_reactive_power, type="n", xlab = "datetime", ylab = "Global_reactive_power"))
lines(ymd_hms(datetime),subPowerData$Global_reactive_power)
dev.off()